### ISSUE TITLE
`chef cook` failure

### ISSUE THREAD

**Issue by cpb-** [cpb-/chef#32]
Calling `chef cook <menu>` fails if `chef init <menu>` was not called first:

```
[Yocto-trees@why-cpb]$ chef cook custom-systems.menu 
Update layers in project directory
Updating source /home/testing/Build/Yocto-trees/sources/poky... 
Updating source /home/testing/Build/Yocto-trees/sources/meta-openembedded... 
Updating source /home/testing/Build/Yocto-trees/sources/meta-sunxi... 
Updating source /home/testing/Build/Yocto-trees/sources/meta-qt5... 
Generating build dirs for target in project directory
Traceback (most recent call last):
  File "/home/cpb/bin/chef", line 460, in <module>
    ChefCall()
  File "/home/cpb/bin/chef", line 213, in __init__
    self.clargs.func() # call function of selected command
  File "/home/cpb/bin/chef", line 232, in cook
    self.prepare()
  File "/home/cpb/bin/chef", line 262, in prepare
    self.generate()
  File "/home/cpb/bin/chef", line 244, in generate
    self.prepare_build_directory(directory, content)
  File "/home/cpb/bin/chef", line 359, in prepare_build_directory
    dl_dir = '${TOPDIR}/' + os.path.relpath(self.config.dl_dir(), path)
  File "/home/cpb/bin/chef", line 95, in dl_dir
    return os.path.join(self.project_root(), self.cfg['dl-dir'])
KeyError: 'dl-dir'
```

**Comment by pboettch** [comment]
Yes, with my dl-dir-fix you need to re-issue a chef init -f in an existing project-dir to have the dl-dir set. Be careful of default values.

**Comment by cpb-** [comment]
I tried to remove the `.chefconfig` file, but it's not better:

```
$ chef cook custom-systems.menu 
Update layers in project directory
Traceback (most recent call last):
  File "/home/cpb/bin/chef", line 460, in <module>
    ChefCall()
  File "/home/cpb/bin/chef", line 213, in __init__
    self.clargs.func() # call function of selected command
  File "/home/cpb/bin/chef", line 232, in cook
    self.prepare()
  File "/home/cpb/bin/chef", line 261, in prepare
    self.update()
  File "/home/cpb/bin/chef", line 254, in update
    self.download_source(source)
  File "/home/cpb/bin/chef", line 290, in download_source
    local_dir = os.path.realpath(self.config.layer_dir(local_dir))
  File "/home/cpb/bin/chef", line 91, in layer_dir
    return os.path.join(self.project_root(), self.cfg['layer-dir'], name)
KeyError: 'layer-dir'
```

I thought that `chef cook <menu>` is the upper-level command that could run without `.chefconfig` file, using defaults values. 

`chef init` is a more advanced command, that user doesn't need to know to just try `chef`.

**Comment by pboettch** [comment]
upper level commands are based on lower level commands and lower level commands use the (loaded, just created) config. Upper level commands have to call them correctly with the arguments. 

Hmm...

**Comment by pboettch** [comment]
We need a test environment so see that the addition/changes of commands do not break other commands.
